// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Fn is an autogenerated mock type for the Fn type
type Fn struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *Fn) Execute() {
	_m.Called()
}

// NewFn creates a new instance of Fn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fn {
	mock := &Fn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
