// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FnWithContext is an autogenerated mock type for the FnWithContext type
type FnWithContext struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *FnWithContext) Execute(_a0 context.Context) {
	_m.Called(_a0)
}

// NewFnWithContext creates a new instance of FnWithContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFnWithContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *FnWithContext {
	mock := &FnWithContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
