// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Error provides a mock function with given fields: ctx, msg, meta
func (_m *Logger) Error(ctx context.Context, msg string, meta interface{}) {
	_m.Called(ctx, msg, meta)
}

// Info provides a mock function with given fields: ctx, msg, meta
func (_m *Logger) Info(ctx context.Context, msg string, meta interface{}) {
	_m.Called(ctx, msg, meta)
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
