name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, Test, Analyze and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Clone Repository
        uses: actions/checkout@master

      - name: Build and Test
        run: make unit-test

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./build/image/Dockerfile
          push: true
          tags: alifsn/ticket-concert-worker-service:latest
  
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/alifsn/worker-service
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f
